version: '3'

services:
  kudelasz:
    build: .
    command: bash -c "
        pip install -r requirements.txt &&
        cd kudelasz && 
        python manage.py makemigrations && p
        ython manage.py migrate && 
        python manage.py runserver 0.0.0.0:8000
      "
    container_name: kudelasz
    volumes:
      - .:/kudelasz
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - web

  mysql:
    image: mysql:latest
    build:
      context: /mysql
    container_name: kudelasz-mysql
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_DATABASE: kudelasz
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root-password
      TZ: "UTC"
    volumes:
      - "/mysql:/var/lib/mysql"
    ports:
      - "3310:3306"
    networks:
      - web

networks:
  web:
    driver: bridge
    name: kudelasz-web